version: '2'

services:
  lovr:
    image: lovr
    build: .
    ports:
      - 2657:2657
    environment:
      PORT: 2657
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/
    volumes: 
      - .:/usr/src/app
    depends_on:
      - mongo
    command: pm2-docker start index.ts --watch
  mongo:
    image: mongo
    # volumes: 
    #   - ~/docker/storage/loVR-mongo:/data/db
    ports:
      - 27017:27017